version: '2'
plugins:
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: false
    config:
      languages:
        - javascript
  eslint:
    enabled: false
    channel: 'eslint-5'
    config:
      extensions:
        - .js
exclude_patterns:
  - 'tests/'
  - 'demo/'
  - 'dist/'
