env:
  global:
    - CODECLIMATE_REPO_TOKEN=3cc5817663e1aff10b3953b557a98ddb0c8d0d4d515c5b0d9a681098d510d05f

language: node_js
node_js:
  - '8.11.3'

cache:
  yarn: true
  directories:
    - ~/.cache

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn install --frozen-lockfile

matrix:
  include:
    - name: 'Unit Tests'
      script: yarn test-ci
      after_success: codeclimate-test-reporter < coverage/lcov.info
